/*
 * Secret Server
 *
 * This is an API of a secret service. You can save your secret by using the API. You can restrict the access of a secret after the certen number of views or after a certen period of time.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"log"

	"github.com/gomodule/redigo/redis"
)

// Redis provides connection to Redis DB
func Redis() (redis.Conn, error) {
	c, err := redis.Dial("tcp", ":6381")
	if err != nil {
		log.Printf("Failed to connect to Redis server!")
		// Dont panic here, show user-friendly message later on webpage
		return nil, err
	}

	if _, err := c.Do("SELECT", 0); err != nil {
		log.Printf("Failed to SELECT Redis DB! Error: %s", err)
		// Dont panic here, show user-friendly message later on webpage
		return nil, err
	}

	// defer c.Close()
	return c, nil
}
